sudo: required
dist: xenial
language: go

go:
  - "1.12.x"

matrix:
  include:
    - os: linux

cache:
  directories:
  - js/node_modules

install:
  - go get -t ./...
  - go get -u github.com/FiloSottile/vendorcheck
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - VERSION=1.17.0 ./ci-scripts/install-golangci-lint.sh
  - npm install
  - npm install --global source-map-support
  - go env -json

script:
  - vendorcheck ./go/...
  - golangci-lint run -c ./go/.golangci.yml ./go/...
  - go vet -all ./go/...
  - make test
  - make build-js-min
  - make test-suite-ts

notifications:
  email:
    - travis@skycoin.net
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
